version: '3.8'

services:
  moe:
    build:
      context: '.'
    container_name: moe
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    networks:
      - moe-network

  postgres:
    container_name: postgresql-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moe
    volumes:
       - "./postgres-moe:/var/lib/postgresql/data"
    networks:
      - moe-network

volumes:
    postgresql-db:
        driver: local

networks:
  moe-network:
   driver: bridge
