version: '3.8'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      - app

  postgres:
    container_name: postgresql-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moe
    volumes:
       - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - app

volumes:
    postgresql-db:
        driver: local

networks:
  app:
   driver: bridge
